version: '3'

vars:
  MILESTONE: trinity
  IMAGE: nuvolaris/nuvolaris-testkit
  REPO: ghcr.io
  TAG: trinity-22.0305.14
  

dotenv: [".env"]

tasks:

  default: echo $REAL_WORKDIR

  setup: true

  enter: > 
    docker run -ti --entrypoint=/usr/bin/xonsh
    --mount type=bind,source=$REAL_WORKDIR,target=/home/nuvolaris/nuvolaris-test
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    {{.REPO}}/{{.IMAGE}}:{{.TAG}}


  build: docker build . -t {{.REPO}}/{{.IMAGE}}:{{.TAG}} 

  buildx-and-push: docker buildx build --platform linux/amd64,linux/arm64 -t {{.REPO}}/{{.IMAGE}}:{{.TAG}}  .devcontainer --push
