version: '3'
  
dotenv: ["../.env"]

tasks:

  default: task -a

  setup: true

  create:
    - task create -d linode
    - task create -d eks
  
  destroy:
    - task destroy -d linode
    - task destroy -d eks

  list:
    - task list -d linode
    - task list -d eks

  config:
    - task config -d linode
    - task config -d eks
