version: '3'

dotenv: ['../../.env']

tasks:

   default: linode-cli lke {{.CLI_ARGS}}

   create: >
      linode-cli lke cluster-create \
         --label=nuvolaris-cluster --region=eu-west \
         --k8s_version=1.21 --node_pools.type=g6-standard-4 --node_pools.count=1

   destroy: | 
      ID=$(linode-cli lke clusters-list --json | jq '.[0].id')
      linode-cli lke cluster-delete $ID

   config: |
      ID=$(linode-cli lke clusters-list --json | jq '.[0].id')
      if linode-cli lke kubeconfig-view $ID --json 2>&1 | grep "Request failed"
      then echo "cluster not yet ready"
      else linode-cli lke kubeconfig-view $ID --json | jq -r '.[].kubeconfig | @base64d' >../../config/linode.kubeconfig
      fi

   list: linode-cli lke clusters-list