apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nuvolaris-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      publicKeyPath: ../../config/id_rsa.pub
