version: '3'

tasks:

  create: eksctl create cluster -f cluster.yml

  destroy: eksctl delete cluster --name nuvolaris-cluster

  list: eksctl get cluster

  config: |
    aws eks update-kubeconfig --kubeconfig ../../config/eks.kubeconfig --name=nuvolaris-cluster
